[package]
name = "vide"
version = "0.1.0"
edition = "2021"

[features]
default = ["ffmpeg"]
ffmpeg = ["vide_ffmpeg"]


[dependencies]
vide_ffmpeg = { path = "../crates/vide_ffmpeg", optional = true }
vide_lib = { path = "../crates/vide_lib" }